service: tracing-demo-serverless


custom:
  region: ${opt:region, env:AWS_REGION, "us-east-1"}
  stage: ${opt:stage, env:STAGE, "localdev"}
  # TODO(Jetpack): Document this option
  jetpack:
    custom: "custom config option" # TODO(Jetpack): REMOVE

# TODO(jetpack): Add offline plugin
plugins:
  modules:
    - serverless-jetpack

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  environment:
    STAGE: ${self:custom.stage}
  timeout: 30 # seconds (`300` max)
  memorySize: 128 # MB value (`1024` default)

functions:
  base:
    handler: src/base.handler
    events: # Use a generic proxy to allow Express app to route.
      - http: ANY /base
      - http: 'ANY /base/{proxy+}'
    # TODO(Jetpack):Document this option
    jetpack:
      function: "function config option" # TODO(Jetpack): REMOVE

# TODO(Jetpack): We're at ye olde "layers require AWS auth" problem.
# https://github.com/serverless/serverless/issues/8187
# layers:
#   layer-express:
#     path: node_modules/express
